sourceUrl: "http://128.32.37.201:8079/api/query"
workerSize: 40
openIO: 10
uuidDest: "uuids.txt"
metadataDest: "data/metadata.txt"
timeseriesDest: "nil"
readMode: 1
writeMode: 2
chunkSize: 10000000
channelBufferSize: 10